#https://docs.spring.io/spring-boot/docs/2.4.1/reference/htmlsingle/#common-application-properties-server
server:
  port: 8443
  ssl:
    key-store: classpath:static/xxx.key
    key-store-password: 123456
    key-store-type: PKCS12
    keyAlias: xxx
    protocol: TLS